base_url = "https://redesign.snehit.dev"

title = "Mellow Clamour"

compile_sass = true

build_search_index = false

minify_html = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true

[extra]

font_include = [
    "Inria+Serif:ital,wght@0,400;1,700",
    "Press+Start+2P&",
    "Archivo+Black",
    "Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000",
    "Syne:wght@700",
    "DM+Serif+Text:ital@0;1",
    "Bebas+Neue",
    "Work+Sans:ital@0;1",
]
