base_url = "https://redesign.snehit.dev"

title = "Mellow Clamour"

compile_sass = true

build_search_index = false

minify_html = true

[markdown]
highlight_code = true

[extra]

font_include = [
    "Inria+Serif:ital,wght@1,700",
    "Press+Start+2P&",
    "Archivo+Black",
]
